version: "3"
services:
  app:
    build:
      args:
        user: marcel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: logbook
    container_name: logbook-app
    restart: unless-stopped
    environment:
      SERVICE_NAME: logbook
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - logbook-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: logbook-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - logbook-network
      
  db:
    image: mysql:5.7
    container_name: logbook-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - logbook-network
      
      
#Docker Networks
networks:
  logbook-network:
    driver: bridge