version: "3"
services:
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: logbook-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - docroot:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
#    networks:
#      - logbooknetwork
      
#  mysql:
#    image: mysql:5.7
#    container_name: mysql
#    restart: unless-stopped
#    volumes:
#      - dbdata:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: logbook
#      MYSQL_ROOT_PASSWORD: logbook
#      MYSQL_PASSWORD: logbook
#      MYSQL_USER: logbook
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    networks:
#      - logbooknetwork
      
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: logbook
    container_name: logbook-app
    restart: unless-stopped
    environment:
      SERVICE_NAME: logbook
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - docroot:/var/www
#    networks:
#      - logbooknetwork
      
      
##Docker Networks
#networks:
#  logbooknetwork:
#    driver: bridge

#connected volumes
volumes:
  docroot:
    driver: local
